image: node:15-buster

cache:
  paths:
    - node_modules

# Fetch dependencies and check files.
check:
  stage: check
  script:
    - yarn
    - yarn check

# Deploy files to server.
deploy:
  stage: deploy
  needs:
    - check
  dependencies: 
    - check
  script:
    - yarn build
    - apt-get update -qq
    - apt-get install -qq git openssh-client
    - echo "$SSH_PRIVATE_KEY" > key
    - chmod 600 key
    - eval `ssh-agent -s`
    - ssh-add key
    - mkdir -p ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - ssh $SSH_HOST -p $SSH_PORT "rm -rf $DEPLOY_DIRECTORY"
    - scp -P $SSH_PORT -prq out $SSH_HOST:$DEPLOY_DIRECTORY
  only:
    - master

stages:
  - check
  - deploy
